### ISSUE TITLE
New LTraceLine broke compilation on android

### ISSUE THREAD

**Issue by Milerius** [kpango/glg#107]
https://github.com/kpango/glg/blob/6cfd022d5fa924304b38df3111014ff289c4cd0e/glg.go#L149

/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:234:4: constant 2147483648 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:241:4: constant 2147483648 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:248:4: constant 2147483648 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:255:4: constant 2147483648 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:262:4: constant 2147483648 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:269:4: constant 2147483648 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:276:4: constant 2147483648 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:284:4: constant 4294967296 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:291:4: constant 4294967296 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:298:4: constant 8589934592 overflows int
/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/pkg/mod/github.com/kpango/glg@v1.6.1/glg.go:298:4: too many errors
gomobile: go build -v -buildmode=c-shared -o=/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-454342767/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 2

used command: `gomobile bind -v --target=android .`

Could you please a normal value for your enumeration ? 

Would be worth it to add also a github actions job that build on all platform just to be sure we are always compatible, using `gomobile` it's should be straightforward

**Comment by Milerius** [comment]
<img width="1792" alt="Capture d’écran 2021-07-16 à 11 21 11" src="https://user-images.githubusercontent.com/21139416/125924990-240d48b7-952b-4f3b-9436-0598626669bc.png">
Thanks for the quick fix @kpango  you rock

**Comment by kpango** [comment]
@Milerius Thank you, too !!!
