### ISSUE TITLE
STD only WARN and up levels

### ISSUE THREAD

**Issue by spolischook** [kpango/glg#111]
I would like to have the ability to show only some of the log levels into the STD out.
Currently, `New` function (constructor) add all levels to the STD by default and it can't be changed (or it can?)

**Comment by kpango** [comment]
Hi, thank you again for your question.
The glg has many chain configuration methods, such as the `SetLevelWriter` and `SetWriter` and `SetMode` and `SetLevelMode` methods.
`SetWriter` overwrites the logging destination for all levels.
`SetLevelWriter` overrides the log output destination for a given level.
`SetMode` changes all level's log mode (NONE, STD, WRITER)
`SetLevelMode` changes log mode (NONE, STD, WRITER) for a given level.

example code
```go
 glg.New().SetMode(glg.NONE).SetLevelMode(glg.WARN, glg.STD)
 or
  glg.New().SetMode(glg.WRITER).SetWriter(io.Discard).SetLevelWriter(glg.WARN, os.Stdout)
```

**Comment by spolischook** [comment]
Perfect! 👍 
I've just added simple helper function:
```go
func setLevel(lLevel glg.LEVEL) {
	for l := lLevel; l <= glg.FATAL; l++ {
		glg.Get().SetLevelMode(l, glg.BOTH)
	}
}
```
And setup logger like that:
```go
		log = glg.Get().
			SetMode(glg.NONE).
			SetLineTraceMode(glg.TraceLineLong)

		setLevel(levelFromString(cfg.LogLevel))
		addSentryWriter(log, cfg.SentryDsn)
		addFileWriter(log, cfg)
```
Used singleton `Get`

Thanks for the really great library and your response in issues!
