### ISSUE TITLE
Logging function returns error affects program test coverage and maintainability

### ISSUE THREAD

**Issue by kevindiu** [kpango/glg#12]
When using logging function provided by glg (for example Print, Printf, Errorf, etc), we have to handle the returned error from the function. It makes the program hard to maintain and affect the implementation of test cases to handle the error properly.

**Comment by kpango** [comment]
Since standard fmt.Print method etc. also returns error, I think that return value of error is mandatory also in order to detect from the API that write to stdout and buffer failed.

**Comment by kevindiu** [comment]
I think both correct (I mean return error or not), because if something cannot be written into disk or buffer which means the computer should have serious problem and the program should be terminated, as you can't write anything to the disk means it is dangerous to lost the information of logging, and it is important in production environment. 

I think we can provide a secondary writer source, to write the message to this writer whenever the main one has errors occurred, and exist the program.

Or we provide a function called something like " onError(f func()) " allowing user to choose what to do when error occurred.

**Comment by kevindiu** [comment]
In user application, I think users use a lot with the logging library, and onError function can help user to simplify the logic inside their code. 
Moreover, when logging function cannot be executed, serious problem should be happened in the OS and most of the case even if user retry, it doesn't work. So I think it is meaningless to return error.
