### ISSUE TITLE
Disable time printing

### ISSUE THREAD

**Issue by vlada-dudr** [kpango/glg#85]
Hello, thank you for nice library!

Is there a way to disable time printing? If one logs to systemd, it is quite redundant as journald adds its own timestamps...

**Comment by kpango** [comment]
Hi!

Thanks for your feedback, I was aiming for the same specification and user experience as Go's standard logs, so we don't currently have such a feature.
However, I will look into the option to disable the time output, as I think the use case you mentioned would certainly be useful.

**Comment by kpango** [comment]
@vlada-dudr added. 
https://github.com/kpango/glg/pull/86

**Comment by vlada-dudr** [comment]
Hi! Thank you, your reaction speed is amazing!

Sadly go mod throws an error at me:
```
go: github.com/kpango/glg@v1.5.6 requires
	github.com/goccy/go-json@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by kpango** [comment]
@vlada-dudr sorry for inconvenient, I updated module dependency at glg v1.5.7 could you please use it?
https://github.com/kpango/glg/releases/tag/v1.5.7

**Comment by vlada-dudr** [comment]
It works. Thank you very much for quick resolution, amazing!
