### ISSUE TITLE
Add ability to set a global loglevel

### ISSUE THREAD

**Issue by peterfraedrich** [kpango/glg#9]
As far as I can see there's no way to set a global log level for `glg`. This should be implemented.

**Comment by kpango** [comment]
Sorry that it may not answer your request.

For now glg can enable / disable logging per log level only.

What you mean is, if glg's global log level set to ERR or FATAL, glg level INFO PRINT DEBUG must be disabled?

**Comment by kpango** [comment]
This Issue will close because there is no response for 2 months.

**Comment by dg424** [comment]
Yes, almost all logging systems implement this. SetLevel(ERR) = only output error messages, SetLevel(DEBUG) = everything.

**Comment by kpango** [comment]
@dg424 Hi, thank you for your comment.
I released glg v1.5.9 which included global log level configuration support.
https://github.com/kpango/glg/releases/tag/v1.5.9

please take look at example code below
https://github.com/kpango/glg/blob/master/example/main.go#L145-L151

**Comment by dg424** [comment]
Hi,
Thanks! I will try this. This feature was preventing me from using this library. Need the ability to turn debug on/off at runtime to gather data while keeping the logging level to a minimum. I assume this does not hurt performance ? i.e. the debug statements should be almost a no-op when a higher log level is set ?

**Comment by kpango** [comment]
@dg424 Basically, there was no performance degradation as I checked in the benchmark, however, I noticed that I can skip the shared BufferPool reference in case of NONE, so I released a new version 1.5.10.
There is no performance degradation in 1.5.10.

**Comment by dg424** [comment]
One other thing that would be useful is going from log level string to level value. i.e. in addition to this function - func (l LEVEL) String() string - we should have a corresponding function that takes a string and returns a level or sets a level based on a string value. The reason is for configuration/configuration files. For instance - glg.Get().SetLevel(glg.ERR) - if I want to set this in a configuration file, what should I set for glg.ERR ?

**Comment by kpango** [comment]
@dg424 Hi, I have just released a minor update version v1.6.0.
This update includes the glg.Atol (ascii to level) interface, which may help you.

**Comment by dg424** [comment]
Hi,
Thanks. I'm actually comparing this library vs logsrus. Essentially I build and run go test -cover which prints out the total time to run through all the unit tests for the app. What I'm noticing is that glg is not really faster than logsrus, they're close with logsrus being better by a little bit. Maybe I'm not using the library right or there is some setting that I need to set to get better performance ? Or maybe my test doesn't last long enough and glg is better over time as it "warms up" ?

**Comment by kpango** [comment]
@dg424 Can you please open another issue?
This issue has already been resolved, so it's better to discuss it in another Issue.
