### ISSUE TITLE
How to use Formatter?

### ISSUE THREAD

**Issue by Luoxin** [kpango/glg#90]

**Comment by kpango** [comment]
Sorry, Could you please describe more about question ??
How can I help you?

**Comment by Luoxin** [comment]
When I use `github.com/sirupsen/logrus`, I can specify the output format of the log via `SetFormatter`, I would like to know if `glg` has a similar function

**Comment by kpango** [comment]
Actually glg doesn't support custom formatter but we provide 2 format (raw, json) you can enable json format style by below code
https://github.com/kpango/glg/blob/master/example/main.go#L163
